name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: make build
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    - name: Run tests
      run: make test
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    - name: Install XcodeGen
      run: brew install xcodegen
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
    - name: Check the example project
      run: make check_example
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
